name: Release publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          npm ci
          npm run build
          npm run test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Extract PACKAGE_VERSION
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Publish
        if: contains(steps.package-version.outputs.current-version, 'dev') != true
        run: |
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@nrchkb'
      - name: Extract PACKAGE_VERSION
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Publish
        if: contains(steps.package-version.outputs.current-version, 'dev') != true
        run: |
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GHUB_TKN}}
      - name: Update Node-Red flow-library
        if: contains(steps.package-version.outputs.current-version, 'dev') != true
        uses: Zehir/update-package-node-red-flow-library-action@v1.0.5
        continue-on-error: true
        with:
          package-name: 'node-red-contrib-homekit-bridged'
